apiVersion: v1
kind: Service
metadata:
  name: nanobot
  labels:
    app: nanobot
spec:
  type: NodePort
  selector:
    app: nanobot
  ports:
  - port: 18790
    targetPort: 18790
    nodePort: 30090
    protocol: TCP
    name: gateway
